apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: static-site-ingress
spec:
  rules:
    - host: static-site.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: static-site-service
                port:
                  number: 80
